import React from "react";
import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function DayLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        {/* You can customize header/footer here */}
        {children}
      </body>
    </html>
  );
}
