// app/layout.tsx (server component)

import type { Metadata } from "next";

import "./globals.css";
import ClientWrapper from "../../../components/ClientWrapper";

export const metadata: Metadata = {
  title: "Visit Track",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
